version: '2'
services:
    spinalexerp-app:
        image: spinalexerp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://spinalexerp-postgresql:5432/spinalexerp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    spinalexerp-postgresql:
        extends:
            file: postgresql.yml
            service: spinalexerp-postgresql
